Error with config: config/conversation/gpt2/distillrecdial.yaml
Exception Traceback:
Traceback (most recent call last):
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/experiments.py", line 32, in <module>
    run_crslab(config,
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/quick_start/quick_start.py", line 56, in run_crslab
    dataset = get_dataset(config, tokenize, restore_data, save_data)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/__init__.py", line 90, in get_dataset
    return dataset_register_table[dataset](opt, tokenize, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/distillrecdial/distillrecdial.py", line 54, in __init__
    super().__init__(opt, dpath, resource, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/base.py", line 45, in __init__
    build(dpath, dfile, version=resource['version'])
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 274, in build
    downloadable_file.download_file(dpath)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 75, in download_file
    download(self.url, dpath, self.file_name)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 142, in download
    raise RuntimeError('Connection broken too many times. Stopped retrying.')
RuntimeError: Connection broken too many times. Stopped retrying.

================================================================================
Error with config: config/crs/redial/distillrecdial.yaml
Exception Traceback:
Traceback (most recent call last):
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/experiments.py", line 32, in <module>
    run_crslab(config,
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/quick_start/quick_start.py", line 56, in run_crslab
    dataset = get_dataset(config, tokenize, restore_data, save_data)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/__init__.py", line 90, in get_dataset
    return dataset_register_table[dataset](opt, tokenize, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/distillrecdial/distillrecdial.py", line 54, in __init__
    super().__init__(opt, dpath, resource, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/base.py", line 45, in __init__
    build(dpath, dfile, version=resource['version'])
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 274, in build
    downloadable_file.download_file(dpath)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 75, in download_file
    download(self.url, dpath, self.file_name)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 142, in download
    raise RuntimeError('Connection broken too many times. Stopped retrying.')
RuntimeError: Connection broken too many times. Stopped retrying.

================================================================================
Error with config: config/crs/inspired/distillrecdial.yaml
Exception Traceback:
Traceback (most recent call last):
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/experiments.py", line 32, in <module>
    run_crslab(config,
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/quick_start/quick_start.py", line 56, in run_crslab
    dataset = get_dataset(config, tokenize, restore_data, save_data)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/__init__.py", line 90, in get_dataset
    return dataset_register_table[dataset](opt, tokenize, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/distillrecdial/distillrecdial.py", line 54, in __init__
    super().__init__(opt, dpath, resource, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/base.py", line 45, in __init__
    build(dpath, dfile, version=resource['version'])
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 274, in build
    downloadable_file.download_file(dpath)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 75, in download_file
    download(self.url, dpath, self.file_name)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 142, in download
    raise RuntimeError('Connection broken too many times. Stopped retrying.')
RuntimeError: Connection broken too many times. Stopped retrying.

================================================================================
Error with config: config/crs/kbrd/distillrecdial.yaml
Exception Traceback:
Traceback (most recent call last):
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/experiments.py", line 32, in <module>
    run_crslab(config,
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/quick_start/quick_start.py", line 37, in run_crslab
    CRS_dataset = get_dataset(config, config['tokenize'], restore_data, save_data)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/__init__.py", line 90, in get_dataset
    return dataset_register_table[dataset](opt, tokenize, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/distillrecdial/distillrecdial.py", line 54, in __init__
    super().__init__(opt, dpath, resource, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/base.py", line 45, in __init__
    build(dpath, dfile, version=resource['version'])
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 274, in build
    downloadable_file.download_file(dpath)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 75, in download_file
    download(self.url, dpath, self.file_name)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 142, in download
    raise RuntimeError('Connection broken too many times. Stopped retrying.')
RuntimeError: Connection broken too many times. Stopped retrying.

================================================================================
Error with config: config/recommendation/bert/distillrecdial.yaml
Exception Traceback:
Traceback (most recent call last):
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/experiments.py", line 32, in <module>
    run_crslab(config,
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/quick_start/quick_start.py", line 56, in run_crslab
    dataset = get_dataset(config, tokenize, restore_data, save_data)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/__init__.py", line 90, in get_dataset
    return dataset_register_table[dataset](opt, tokenize, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/distillrecdial/distillrecdial.py", line 54, in __init__
    super().__init__(opt, dpath, resource, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/base.py", line 45, in __init__
    build(dpath, dfile, version=resource['version'])
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 274, in build
    downloadable_file.download_file(dpath)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 75, in download_file
    download(self.url, dpath, self.file_name)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 142, in download
    raise RuntimeError('Connection broken too many times. Stopped retrying.')
RuntimeError: Connection broken too many times. Stopped retrying.

================================================================================
Error with config: config/recommendation/gru4rec/distillrecdial.yaml
Exception Traceback:
Traceback (most recent call last):
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/experiments.py", line 32, in <module>
    run_crslab(config,
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/quick_start/quick_start.py", line 56, in run_crslab
    dataset = get_dataset(config, tokenize, restore_data, save_data)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/__init__.py", line 90, in get_dataset
    return dataset_register_table[dataset](opt, tokenize, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/distillrecdial/distillrecdial.py", line 54, in __init__
    super().__init__(opt, dpath, resource, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/base.py", line 45, in __init__
    build(dpath, dfile, version=resource['version'])
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 274, in build
    downloadable_file.download_file(dpath)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 75, in download_file
    download(self.url, dpath, self.file_name)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 142, in download
    raise RuntimeError('Connection broken too many times. Stopped retrying.')
RuntimeError: Connection broken too many times. Stopped retrying.

================================================================================
Error with config: config/recommendation/popularity/distillrecdial.yaml
Exception Traceback:
Traceback (most recent call last):
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/experiments.py", line 32, in <module>
    run_crslab(config,
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/quick_start/quick_start.py", line 56, in run_crslab
    dataset = get_dataset(config, tokenize, restore_data, save_data)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/__init__.py", line 90, in get_dataset
    return dataset_register_table[dataset](opt, tokenize, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/distillrecdial/distillrecdial.py", line 54, in __init__
    super().__init__(opt, dpath, resource, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/base.py", line 45, in __init__
    build(dpath, dfile, version=resource['version'])
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 274, in build
    downloadable_file.download_file(dpath)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 75, in download_file
    download(self.url, dpath, self.file_name)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 142, in download
    raise RuntimeError('Connection broken too many times. Stopped retrying.')
RuntimeError: Connection broken too many times. Stopped retrying.

================================================================================
Error with config: config/recommendation/sasrec/distillrecdial.yaml
Exception Traceback:
Traceback (most recent call last):
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/experiments.py", line 32, in <module>
    run_crslab(config,
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/quick_start/quick_start.py", line 56, in run_crslab
    dataset = get_dataset(config, tokenize, restore_data, save_data)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/__init__.py", line 90, in get_dataset
    return dataset_register_table[dataset](opt, tokenize, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/distillrecdial/distillrecdial.py", line 54, in __init__
    super().__init__(opt, dpath, resource, restore, save)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/data/dataset/base.py", line 45, in __init__
    build(dpath, dfile, version=resource['version'])
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 274, in build
    downloadable_file.download_file(dpath)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 75, in download_file
    download(self.url, dpath, self.file_name)
  File "/leonardo_work/IscrC_LLM-REC/ale/CRSLab/crslab/download.py", line 142, in download
    raise RuntimeError('Connection broken too many times. Stopped retrying.')
RuntimeError: Connection broken too many times. Stopped retrying.

================================================================================
